# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6394bbe51cc1aa1a5776475779a40f8690aae872f4348cd131745f533db9c00973096d3a02f41950de48e886576a889dcb1fbd9912dc67c0003d61ff87786d21

test:
  secret_key_base: ddd1b5a86bd24acd5134a276269ef07b6f460d2bb3a91801772295247edd11a29f1ea5f8333043df37729d3cf5c4c97f40e17300c7e0426b053186453e80d68b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
